server:
  port: 8888

spring:
  application:
    name: config-server
  security:
    user:
      name: config
      password: config123
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yallisonmelo/Distributed-systems-configs.git
          default-label: main